import { Stock } from './stock';

export var STOCKS: Stock[] = [
  {ticker: 'SQ',
  price: 0,
  company: 'Square Inc.',
  returns: 0,
  june15: 91.00,
  marketCap: 45.95,
  logo:''
  },
  {ticker: 'V',
  price: 0,
  company: 'Visa Inc.',
  returns: 0,
  june15: 191.76,
  marketCap: 0,
  logo:''
  },
  {ticker: 'LUV',
  price: 0,
  company: 'Southwest Airlines Co.',
  returns: 0,
  june15: 36.34,
  marketCap: 0,
  logo:'../assets/luv.png'
  },
  {ticker: 'LAUR',
  price: 0,
  company: 'Laureate Education Inc.',
  returns: 0,
  june15: 10.15,
  marketCap: 0,
  logo:''
  },
  {ticker: 'OMC',
  price: 0,
  company: 'Omnicom Group Inc.',
  returns: 0,
  june15: 56.32,
  marketCap: 0,
  logo:''
  },
  {ticker: 'AAPL',
  price: 0,
  company: 'Apple Inc.',
  returns: 0,
  june15: 342.99,
  marketCap: 0,
  logo:''
  },
  {ticker: 'CAKE',
  price: 0,
  company: 'The Cheesecake Factory Inc.',
  returns: 0,
  june15: 25.13,
  marketCap: 0,
  logo:''
  },
  {ticker: 'ABC',
  price: 0,
  company: 'AmerisourceBergen Corp.',
  returns: 0,
  june15: 96.21,
  marketCap: 0,
  logo:'../assets/ABC.png'
  },
  {ticker: 'PANW',
  price: 0,
  company: 'Palo Alto Networks Inc.',
  returns: 0,
  june15: 226.30,
  marketCap: 0,
  logo:'../assets/PAN.png'
  },
  {ticker: 'RVLV',
  price: 0,
  company: 'Revolve Group LLC.',
  returns: 0,
  june15: 15.32,
  marketCap: 0,
  logo:'../assets/revolve.jpeg'
  },
  {ticker: 'ZM',
  price: 0,
  company: 'Zoom Video Communications Inc.',
  returns: 0,
  june15: 239.02,
  marketCap: 0,
  logo:''
  },
  {ticker: 'W',
  price: 0,
  company: 'Wayfair Inc.',
  returns: 0,
  june15: 193.19,
  marketCap: 0,
  logo:''
  },
  {ticker: 'SPOT',
  price: 0,
  company: 'Spotify Technology S.A.',
  returns: 0,
  june15: 187.88,
  marketCap: 0,
  logo: '../assets/Spotifylogo.png'
  },
  {ticker: 'XSPA',
  price: 0,
  company: 'XpresSpa Group, Inc.',
  returns: 0,
  june15: 5.50,
  marketCap: 0,
  logo:'../assets/xspa.png'
  }
];
