import { Stock } from './stock';

export var STOCKS: Stock[] = [
  {ticker: 'SQ',
  price: 97,
  company: 'Square Inc.',
  rank: 0,
  returns: 0,
  rise: true,
  marketCap: 45.95,
  peRatio: 157
  },
  {ticker: 'VISA',
  price: 0,
  company: 'Visa Inc.',
  rank: 3,
  returns: 0,
  rise: true,
  marketCap: 0,
  peRatio: 0
  },
  {ticker: 'LUV',
  price: 0,
  company: 'Southwest Airlines Co.',
  rank: 0,
  returns: 0,
  rise: true,
  marketCap: 0,
  peRatio: 0
  },
  {ticker: 'LAUR',
  price: 0,
  company: 'Laureate Education Inc.',
  rank: 3,
  returns: 0,
  rise: true,
  marketCap: 0,
  peRatio: 0
  },
  {ticker: 'OMC',
  price: 0,
  company: 'Omnicom Group Inc.',
  rank: 3,
  returns: 0,
  rise: true,
  marketCap: 0,
  peRatio: 0
  },
  {ticker: 'AAPL',
  price: 0,
  company: 'Apple Inc.',
  rank: 3,
  returns: 0,
  rise: true,
  marketCap: 0,
  peRatio: 0
  },
  {ticker: 'VISA',
  price: 0,
  company: 'Visa',
  rank: 3,
  returns: 0,
  rise: true,
  marketCap: 0,
  peRatio: 0
  },
  {ticker: 'CAKE',
  price: 0,
  company: 'The Cheesecake Factory Inc.',
  rank: 3,
  returns: 0,
  rise: true,
  marketCap: 0,
  peRatio: 0
  },
  {ticker: 'ABC',
  price: 0,
  company: 'AmerisourceBergen Corp.',
  rank: 3,
  returns: 0,
  rise: true,
  marketCap: 0,
  peRatio: 0
  },
  {ticker: 'PANW',
  price: 0,
  company: 'Palo Alto Networks Inc.',
  rank: 3,
  returns: 0,
  rise: true,
  marketCap: 0,
  peRatio: 0
  },
  {ticker: 'VISA',
  price: 0,
  company: 'Visa',
  rank: 3,
  returns: 0,
  rise: true,
  marketCap: 0,
  peRatio: 0
  },
  {ticker: 'RVLV',
  price: 0,
  company: 'Revolve Group LLC.',
  rank: 3,
  returns: 0,
  rise: true,
  marketCap: 0,
  peRatio: 0
  },
  {ticker: 'VISA',
  price: 0,
  company: 'Visa',
  rank: 3,
  returns: 0,
  rise: true,
  marketCap: 0,
  peRatio: 0
  },
  {ticker: 'ZM',
  price: 0,
  company: 'Zoom Video Communications Inc.',
  rank: 3,
  returns: 0,
  rise: true,
  marketCap: 0,
  peRatio: 0
  },
  {ticker: 'W',
  price: 0,
  company: 'Wayfair Inc.',
  rank: 3,
  returns: 0,
  rise: true,
  marketCap: 0,
  peRatio: 0
  },
  {ticker: 'SPOT',
  price: 0,
  company: 'Spotify Technology S.A.',
  rank: 3,
  returns: 0,
  rise: true,
  marketCap: 0,
  peRatio: 0
  },
  {ticker: 'XSPA',
  price: 0,
  company: 'XpresSpa Group, Inc.',
  rank: 3,
  returns: 0,
  rise: true,
  marketCap: 0,
  peRatio: 0
  }
];
